# Generated by Django 6.0.2 on 2026-02-15 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('editors', models.ManyToManyField(blank=True, related_name='publisher_editor_of', to=settings.AUTH_USER_MODEL)),
                ('journalists', models.ManyToManyField(blank=True, related_name='publisher_journalist_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

