# Generated by Django 6.0.2 on 2026-02-15 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='news.publisher'),
        ),
    ]
